- name: convert hosts from csv
  hosts: localhost
  connection: local
  remote_user: root
  gather_facts: false
  become: false
  vars:
    vcenter_ip: "{{ var1 }}"
    vcenter_username: "{{ var2 }}"
    vcenter_password: " {{ var3 }}"
    vcenter_cluster: "{{ var4 }}"
    vcenter_dc: "{{ var5 }}"
    vm_name: "{{ var6 }}"
    vcenter_template: "{{ var7 }}"
    vcenter_datastore: "{{ var8 }}"
    vm_network: "{{ var9 }}"
    vm_ip: "{{ var10 }}"
    vm_netmask: "{{ var11 }}"
    vm_gw: "{{ var12 }}"
    hostips_hostipmacs: "{{ var13 }}"
  tasks:
    - name: create VM
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_dc }}"
        folder: /myfolder_1
        name: "{{ vm_name  }}"
        state: poweredon
        template: "{{ vcenter_template }}"
        disk:
        - size_gb: 55
          type: thin
          datastore: "{{ vcenter_datastore }}"
        hardware:
          memory_mb: 512
          num_cpus: 1
        networks:
        - name: "{{ vm_network }}"
          type: "static"
          ip: "{{ vm_ip }}"
          netmask: "{{ vm_netmask }}"
          gateway: "{{ vm_gw }}"
        wait_for_ip_address: no
