- name: convert hosts from csv
  hosts: localhost
  connection: local
  remote_user: root
  gather_facts: false
  become: false
  vars:
    vcenter_ip: "{{ var1 }}"
    vcenter_username: "{{ var2 }}"
    vcenter_password: " {{ var3 }}"
    vcenter_cluster: "{{ var4 }}"
    vcenter_dc: "{{ var5 }}"
    vm_name: "{{ var6 }}"
    vcenter_template: Linux_temp
    vcenter_datastore: MCIT_DS_17
    vm_network: "VM Network"
    vm_ip: "{{ var7 }}"
    vm_netmask: "{{ var8 }}"
    vm_gw: "{{ var9 }}"
  tasks:
    - name: create VM
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_dc }}"
        folder: /cf
        name: "{{ vm_name  }}"
        state: poweredon
        template: "{{ vcenter_template }}"
        disk:
        - size_gb: 55
          type: thin
          datastore: "{{ vcenter_datastore }}"
        hardware:
          memory_mb: 512
          num_cpus: 1
        networks:
        - name: "{{ vm_network }}"
          type: "static"
          ip: "{{ vm_ip }}"
          netmask: "{{ vm_netmask }}"
          gateway: "{{ vm_gw }}"
        wait_for_ip_address: no
